apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acme-web 
  name: acme-web
  namespace: acme-air
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acme-web
    spec:
      affinity: {}
      containers:
      - args:
        - npm
        - start
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: PORT
          value: "3000"
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        image: garreeoke/acmenode:56
        imagePullPolicy: Always
        name: acme-web
        ports:
        - containerPort: 3000
          name: http-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http-port
        readinessProbe:
          httpGet:
            path: /
            port: http-port
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
