apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-web
  namespace: acme-air
spec:
  rules:
  - host: acme-air.armory.garreeoke.io
    http:
      paths:
      - backend:
          serviceName: acme-web
          servicePort: 3000
